# Generated by Django 2.1.5 on 2019-02-19 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='problem',
            field=models.ManyToManyField(related_name='tags', to='problem.Problem', verbose_name='problem'),
        ),
    ]
