# Generated by Django 2.1.5 on 2019-02-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20190218_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='type',
            field=models.CharField(choices=[('DIF', 'Difficulty'), ('THEME', 'Theme')], default='THEME', max_length=5),
        ),
    ]
