# Generated by Django 2.1.5 on 2019-02-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('code', models.CharField(default='', max_length=5000)),
                ('problem', models.ManyToManyField(related_name='template', to='problem.Problem', verbose_name='problem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
