# Generated by Django 2.1.5 on 2019-02-18 20:12

import business_judge.test_case.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('number', models.IntegerField(default=0)),
                ('file_input', models.FileField(upload_to=business_judge.test_case.models.directory_path_input)),
                ('file_output', models.FileField(upload_to=business_judge.test_case.models.directory_path_output)),
                ('explanation', models.CharField(default='', max_length=500)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case', to='problem.Problem', verbose_name='problem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
