# Generated by Django 2.1.5 on 2019-02-18 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
        ('test_case', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestCase',
            new_name='TestCaseModel',
        ),
    ]
