# Generated by Django 2.1.5 on 2019-02-19 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_case', '0002_auto_20190218_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasemodel',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testcasemodel',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='problem.Problem', verbose_name='problem'),
        ),
    ]
