# Generated by Django 2.1.5 on 2019-02-18 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('statement', models.CharField(default='', max_length=1500)),
                ('input_format', models.CharField(default='', max_length=500)),
                ('output_format', models.CharField(default='', max_length=500)),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='problem.Problem', verbose_name='problem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
