# Generated by Django 2.1 on 2018-09-08 22:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(default='', max_length=500)),
                ('input_format', models.CharField(default='', max_length=500)),
                ('output_format', models.CharField(default='', max_length=500)),
                ('explanation', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=200)),
                ('time_stamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('max_score', models.FloatField(null=True)),
                ('difficulty', models.CharField(max_length=30, null=True)),
                ('time_limit', models.FloatField(default=1.0)),
                ('theme', models.CharField(default='', max_length=100)),
                ('template', models.CharField(default='', max_length=5000)),
                ('link_source', models.CharField(default='', max_length=100)),
                ('is_original', models.BooleanField(default=False)),
                ('description', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.Description')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.CharField(max_length=30)),
                ('rol', models.IntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.CharField(max_length=1000)),
                ('veredict', models.CharField(choices=[('QUE', 'Queue'), ('JUD', 'Judging'), ('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TL', 'Time limit'), ('RTE', 'Run Time Error'), ('CE', 'Compilation Error')], default='QUE', max_length=4)),
                ('time_stamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
