# Generated by Django 2.1 on 2018-09-09 14:07

import App.description.model
import App.submission.model
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_reply', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(default='', max_length=500)),
                ('input_format', models.CharField(default='', max_length=500)),
                ('output_format', models.CharField(default='', max_length=500)),
                ('explanation', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=200)),
                ('time_stamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('max_score', models.FloatField(null=True)),
                ('difficulty', models.IntegerField(default=1)),
                ('time_limit', models.FloatField(default=1.0)),
                ('theme', models.CharField(default='', max_length=100)),
                ('template', models.CharField(default='', max_length=5000)),
                ('link_source', models.CharField(default='', max_length=100)),
                ('is_original', models.BooleanField(default=False)),
                ('description', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.Description')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.CharField(default='N/A', max_length=30)),
                ('rol', models.IntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QueueSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veredict', models.CharField(choices=[('QUE', 'Queue'), ('JUD', 'Judging'), ('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TL', 'Time limit'), ('RTE', 'Run Time Error'), ('CE', 'Compilation Error')], default='QUE', max_length=4)),
                ('score', models.FloatField(default=0.0)),
                ('time_stamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('source_code', models.FileField(upload_to=App.submission.model.directory_path)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fileIn', models.FileField(upload_to=App.description.model.directory_path)),
                ('fileOut', models.FileField(upload_to=App.description.model.directory_path)),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Description')),
            ],
        ),
        migrations.AddField(
            model_name='queuesubmission',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Submission'),
        ),
        migrations.AddField(
            model_name='comment',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Problem'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
