# Generated by Django 2.1.5 on 2019-02-18 20:12

import business_judge.submission.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('verdict', models.CharField(choices=[('QUE', 'Queue'), ('JUD', 'Judging'), ('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TL', 'Time limit'), ('RTE', 'Run Time Error'), ('CE', 'Compilation Error')], default='QUE', max_length=4)),
                ('time_stamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('source_code', models.FileField(upload_to=business_judge.submission.models.directory_submissions_path)),
                ('cases_passed', models.IntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='problem.Problem', verbose_name='problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
