# Generated by Django 2.1.5 on 2019-02-24 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='time_stamp',
        ),
    ]
