# Generated by Django 2.1.5 on 2019-02-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_remove_submission_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('PY3', 'Python3'), ('PY2', 'python2'), ('CPP', 'C++')], default='PY3', max_length=5),
        ),
    ]
